name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'hkpatch/tailscale-android-modify-v1'
          platform: 'github'
          ref: 'main'

      - name: build
        run: |
          docker build -t tailscale-android-modify-v1 .
          docker run -v ${PWD}:/build/tailscale-android-modify-v1 --rm tailscale-android-modify-v1 make mesh-debug.apk
 
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          tag_name: latest
          files: mesh-debug.apk
          release: true
          repository: ${{ github.actor }}/tailscale-android-modify-v1
